/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from 'react';

export const Index: Record<string, any> = {
  'use-window-size': {
    name: 'use-window-size',
    description: 'A hook to get the window size',
    type: 'registry:hook',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/hooks/use-window-size.tsx',
        type: 'registry:hook',
        target: 'hooks/ez-hooks/use-window-size.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/hooks/use-window-size.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object',
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  'use-window-size-demo': {
    name: 'use-window-size-demo',
    description: "Hook to get the current window's size.",
    type: 'registry:example',
    registryDependencies: ['https://ez-hooks.vercel.app/r/use-window-size'],
    files: [
      {
        path: 'registry/examples/use-window-size-demo.tsx',
        type: 'registry:example',
        target: 'components/examples/use-window-size-demo.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/examples/use-window-size-demo.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === 'function' || typeof mod[key] === 'object',
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
};
